SET TALK ON
SET NOTIFY ON
SET CLOCK OFF
&& RecentlyUsedFiles = 4
SET COMPATIBLE OFF
SET PALETTE ON
SET BELL ON
SET BELL TO '', 1
SET SAFETY ON
SET ESCAPE ON
SET LOGERRORS ON
SET KEYCOMP TO WINDOWS
SET CARRY OFF
SET CONFIRM OFF
SET BROWSEIMECONTROL OFF
SET STRICTDATE TO 1
&& TabOrdering = 0
&& ResWidth = 640
&& ResHeight = 480
&& GridHorz = 12
&& GridVert = 12
&& ScaleUnits = 0
&& FormSetLib = 
&& FormSetClass = 
&& FormsLib = 
&& FormsClass = 
SET EXACT ON
SET NEAR OFF
SET ANSI OFF
SET LOCK OFF
SET EXCLUSIVE OFF
SET MULTILOCKS OFF
SET HEADINGS ON
SET DELETED OFF
SET OPTIMIZE ON
SET UNIQUE OFF
SET CPDIALOG ON
SET REFRESH TO 0,5
SET ODOMETER TO 100
SET BLOCKSIZE TO 64
SET REPROCESS TO 0
SET COLLATE TO ""
&& SCCProvider = 
STORE "C:\DOCUMENTS AND SETTINGS\ADMIN\MIS DOCUMENTOS\MI MÚSICA\VISUAL FOX PRO 6 0 (ESPAÑOL)\VFP98\SCCTEXT.PRG" TO _SCCTEXT
&& ProjectHookLib = 
&& ProjectHookClass = 
&& CrsBuffering = 1
&& CrsMethodUsed = 1
&& CrsWhereClause = 3
&& CrsFetchSize = 100
&& CrsMaxRows = -1
&& CrsNumBatch = 1
&& CrsUseMemoSize = 255
&& SQLDispLogin = 1
&& SQLTransactions = 1
&& SQLConnectTimeOut = 15
&& SQLIdleTimeOut = 0
&& SQLQueryTimeOut = 0
&& SQLWaitTime = 100
&& TMPFILES = c:\docume~1\walter\config~1\temp
SET PATH TO 
&& HelpTo = c:\archivos de programa\microsoft visual foxpro 7\foxhelp.chm
&& HelpCollection = 
SET HELP ON
*SET HELP COLLECTION 
SET HELP TO "c:\archivos de programa\microsoft visual foxpro 7\foxhelp.chm"
&& ResourceTo = c:\documents and settings\walter\datos de programa\microsoft\visual foxpro\foxuser.dbf
SET RESOURCE ON
SET RESOURCE TO "c:\documents and settings\walter\datos de programa\microsoft\visual foxpro\foxuser.dbf"
STORE "C:\ARCHIVOS DE PROGRAMA\MICROSOFT VISUAL FOXPRO 7\WIZARD.APP" TO _WIZARD
STORE "C:\ARCHIVOS DE PROGRAMA\MICROSOFT VISUAL FOXPRO 7\BUILDER.APP" TO _BUILDER
STORE "C:\ARCHIVOS DE PROGRAMA\MICROSOFT VISUAL FOXPRO 7\CONVERT.APP" TO _CONVERTER
STORE "C:\ARCHIVOS DE PROGRAMA\MICROSOFT VISUAL FOXPRO 7\GENMENU.PRG" TO _GENMENU
STORE "C:\ARCHIVOS DE PROGRAMA\MICROSOFT VISUAL FOXPRO 7\BROWSER.APP" TO _BROWSER
STORE "C:\ARCHIVOS DE PROGRAMA\MICROSOFT VISUAL FOXPRO 7\GALLERY.APP" TO _GALLERY
STORE "" TO _INCLUDE
STORE "C:\ARCHIVOS DE PROGRAMA\MICROSOFT VISUAL FOXPRO 7\BEAUTIFY.APP" TO _BEAUTIFY
STORE "" TO _GETEXPR
STORE "C:\ARCHIVOS DE PROGRAMA\MICROSOFT VISUAL FOXPRO 7\GENHTML.PRG" TO _GENHTML
STORE "C:\ARCHIVOS DE PROGRAMA\MICROSOFT VISUAL FOXPRO 7\RUNACTD.PRG" TO _RUNACTIVEDOC
STORE "" TO _STARTUP
STORE "C:\ARCHIVOS DE PROGRAMA\MICROSOFT VISUAL FOXPRO 7\SAMPLES\" TO _SAMPLES
STORE "C:\ARCHIVOS DE PROGRAMA\MICROSOFT VISUAL FOXPRO 7\COVERAGE.APP" TO _COVERAGE
STORE "C:\ARCHIVOS DE PROGRAMA\MICROSOFT VISUAL FOXPRO 7\TASKLIST.APP" TO _TASKLIST
STORE "C:\ARCHIVOS DE PROGRAMA\MICROSOFT VISUAL FOXPRO 7\OBJECTBROWSER.APP" TO _OBJECTBROWSER
STORE "C:\DOCUMENTS AND SETTINGS\WALTER\DATOS DE PROGRAMA\MICROSOFT\VISUAL FOXPRO\FOXCODE.DBF" TO _FOXCODE
STORE "C:\ARCHIVOS DE PROGRAMA\MICROSOFT VISUAL FOXPRO 7\FOXCODE.APP" TO _CODESENSE
STORE "C:\DOCUMENTS AND SETTINGS\WALTER\DATOS DE PROGRAMA\MICROSOFT\VISUAL FOXPRO\FOXTASK.DBF" TO _FOXTASK
STORE "C:\ARCHIVOS DE PROGRAMA\MICROSOFT VISUAL FOXPRO 7\VFPXTAB.PRG" TO _GENXTAB
SET SYSFORMATS OFF
SET SECONDS ON
SET CENTURY ON
&& CurrSymbol = $
SET CURRENCY LEFT
SET CURRENCY TO "$"
SET HOURS TO 12
SET DATE TO AMERICAN
SET DECIMALS TO 2
SET FDOW TO 1
SET FWEEK TO 1
SET MARK TO ""
SET SEPARATOR TO ","
SET POINT TO "."
&& DebugEnvironment = 0
SET TRBETWEEN OFF
STORE     0.00 TO _THROTTLE
&& DebugOutputFileName = 
&& TraceFontName = Courier New
&& TraceFontSize = 10
&& TraceFontStyle = 0
&& WatchFontName = MS Sans Serif
&& WatchFontSize = 8
&& WatchFontStyle = 0
&& LocalsFontName = MS Sans Serif
&& LocalsFontSize = 8
&& LocalsFontStyle = 0
&& OutputFontName = MS Sans Serif
&& OutputFontSize = 8
&& OutputFontStyle = 0
&& CallstackFontName = MS Sans Serif
&& CallstackFontSize = 8
&& CallstackFontStyle = 0
&& TraceNormalColor = RGB(0,0,0,255,255,255), Auto, Auto
&& TraceExecutingColor = RGB(255,255,0,0,0,0), NoAuto, Auto
&& TraceCallstackColor = RGB(0,0,0,236,233,216), Auto, Auto
&& TraceBreakpointColor = RGB(255,0,0,0,0,0), NoAuto, Auto
&& TraceSelectedColor = RGB(255,255,255,0,0,0), Auto, Auto
&& WatchNormalColor = RGB(0,0,0,255,255,255), Auto, Auto
&& WatchSelectedColor = RGB(255,255,255,0,0,0), Auto, Auto
&& WatchChangedColor = RGB(255,0,0,255,255,255), NoAuto, Auto
&& LocalsNormalColor = RGB(0,0,0,255,255,255), Auto, Auto
&& LocalsSelectedColor = RGB(255,255,255,0,0,0), Auto, Auto
&& OutputNormalColor = RGB(0,0,0,255,255,255), Auto, Auto
&& OutputSelectedColor = RGB(255,255,255,0,0,0), Auto, Auto
&& CallstackNormalColor = RGB(0,0,0,255,255,255), Auto, Auto
&& CallstackSelectedColor = RGB(255,255,255,0,0,0), Auto, Auto
&& BookmarkColor = RGB(0,255,255,0,0,0), NoAuto, Auto
&& ShortcutColor = RGB(0,0,255,0,0,0), NoAuto, Auto
&& EditorCommentString = *!*
&& DisplayCount = 15
&& ParensHighlightDuration = 1500
PUBLIC p as String, c as String
PUBLIC mon1 as String
set default to d:\nfox
open database caja
DO FORM frmacceso.scx
